name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: "1.19.3"

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v2

      - name: Git LFS Pull
        run: git lfs pull

      - name: Go cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-gov2-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gov2-

      - name: Install dependencies
        run: |
          sudo apt-get install make protobuf-compiler
          make .install-bin-deps
          go mod download

      - name: Run build
        run: make

      - name: Run testing
        run: make test
